name: Release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true

env:
  BINARY_NAME: metsysd

jobs:
  check:
    name: Quality
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Package Check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Format Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Linting Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
  build:
    needs: [check]
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
        include:
          - target: aarch64-unknown-linux-gnu
            label: arm
          - target: x86_64-unknown-linux-gnu
            label: amd
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: "Renamed binary"
        run: mv "target/${{ matrix.target }}/release/${{ env.BINARY_NAME }}" "${{ env.BINARY_NAME }}-${{ matrix.label }}-${{ github.ref_name }}"

      - name: Upload binary to release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "${{ env.BINARY_NAME }}-${{ matrix.label }}-${{ github.ref_name }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}